### Уровень 0

1) Придумайте матрицы, которые обладают следующими свойствами:

- a) диагональная, ортогональная, но не единичная(!):
- b) верхнетреугольная, ортогональная:
- c) нижнетреугольная, ортогональная:
- d) матрица, у которой определитель = 1, и все элементы не равны 0:"

*P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!*

2) Найдите собственные значения и собственные вектора матриц

In [1]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

In [118]:
# a) диагональная и ортогональная
x = [[0,0,1], [0,1,0], [1,0,0]]
diag_ort = np.matrix(diag_ort)
diag_ort

matrix([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])

In [119]:
# Проверка матрицы на ортогональность: определитель равен единице
np.linalg.det(diag_ort)

-1.0

In [100]:
# b) верхнетреугольная, ортогональная
# берем любую матрицу
m = [[ 3, 8, 4],
       [ 7, 2, 6],
       [ 1, 5, 9]]
x = np.matrix(m)
x

matrix([[3, 8, 4],
        [7, 2, 6],
        [1, 5, 9]])

In [116]:
# делаем svd разложение, получаем оргтогональные матрицы U, V 
U, s, V = np.linalg.svd(x)
# делаем разложение матрицы U на ортогональную и верхнетреугольную матрицу (произведение орт матриц дает ортогональную)
upper_trian_ort = np.linalg.qr(U, mode = 'r')
upper_trian_ort

matrix([[ 1.00000000e+00, -2.77555756e-16,  2.22044605e-16],
        [ 0.00000000e+00,  1.00000000e+00, -8.32667268e-17],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [117]:
# проверка ортогональности
#n = upper_trian_ort.T
#n.dot(upper_trian_ort)
np.linalg.det(upper_trian_ort)

1.0000000000000004

In [115]:
# c) нижнетреугольная, ортогональная:
lower_trian_ort = np.transpose(y)
lower_trian_ort

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-2.77555756e-16,  1.00000000e+00,  0.00000000e+00],
        [ 2.22044605e-16, -8.32667268e-17,  1.00000000e+00]])

In [113]:
# d) матрица, у которой определитель = 1, и все элементы не равны 0:"
z = np.linalg.qr(U, mode = 'reduced')
z[0]

matrix([[-0.55931196,  0.45021641, -0.69604261],
        [-0.5350512 , -0.83740203, -0.11170523],
        [-0.63315902,  0.30994036,  0.7092578 ]])

In [114]:
np.linalg.det(z[0])

1.0000000000000004

In [120]:
# 2) Найдите собственные значения и собственные вектора матриц
m = np.array([[2, 2],
[1, 3]])
print(m)

[[2 2]
 [1 3]]


In [126]:
def value_vector(matrix):
    
    value, vector = np.linalg.eig(matrix)
    for i in range(len(value)):
        print("Собственное значение " + str(value[i]))
        print("Cобственный вектор для этого значения " + str(vector[:,i]))

In [127]:
value_vector(m)

Собственное значение 1.0
Cобственный вектор для этого значения [-0.89442719  0.4472136 ]
Собственное значение 4.0
Cобственный вектор для этого значения [-0.70710678 -0.70710678]


In [128]:
value_vector(diag_ort)

Собственное значение 1.0
Cобственный вектор для этого значения [[0.70710678]
 [0.        ]
 [0.70710678]]
Собственное значение -1.0
Cобственный вектор для этого значения [[-0.70710678]
 [ 0.        ]
 [ 0.70710678]]
Собственное значение 1.0
Cобственный вектор для этого значения [[0.]
 [1.]
 [0.]]


In [129]:
value_vector(upper_trian_ort)

Собственное значение 0.9999999999999998
Cобственный вектор для этого значения [[1.]
 [0.]
 [0.]]
Собственное значение 1.0000000000000004
Cобственный вектор для этого значения [[-0.38461538]
 [ 0.92307692]
 [ 0.        ]]
Собственное значение 1.0000000000000002
Cобственный вектор для этого значения [[0.24135945]
 [0.34074275]
 [0.90864734]]


In [131]:
value_vector(lower_trian_ort)

Собственное значение 1.0000000000000002
Cобственный вектор для этого значения [[0.]
 [0.]
 [1.]]
Собственное значение 1.0000000000000004
Cобственный вектор для этого значения [[0.        ]
 [0.93632918]
 [0.35112344]]
Собственное значение 0.9999999999999998
Cобственный вектор для этого значения [[ 0.8601567 ]
 [ 0.35839862]
 [-0.36287861]]


In [132]:
value_vector(z[0])

Собственное значение (1.0000000000000002+0j)
Cобственный вектор для этого значения [[ 0.39276129+0.j]
 [-0.05857583+0.j]
 [-0.91777309+0.j]]
Собственное значение (-0.8437280917882347+0.5367708143401466j)
Cобственный вектор для этого значения [[-0.0162959 +0.65007979j]
 [-0.70589265+0.j        ]
 [ 0.03807896+0.27820185j]]
Собственное значение (-0.8437280917882347-0.5367708143401466j)
Cобственный вектор для этого значения [[-0.0162959 -0.65007979j]
 [-0.70589265-0.j        ]
 [ 0.03807896-0.27820185j]]
